# Generated by Django 3.2.7 on 2023-02-19 13:47

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', embed_video.fields.EmbedVideoField()),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-posted'],
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
